### ISSUE TITLE
about datasets

### ISSUE THREAD

**Issue by pandascd** [SparkTempest/Bi-directional-Adapter#11]
I want to know if you used both the LasHeR and Visevent datasets during your training process. Through debugging, I found that it seems only the LasHeR dataset was used. However, with this approach, the results obtained from Lasher_test are PR 59 and SR 46. I’m wondering where I might have gone wrong?

**Comment by SparkTempest** [comment]
We only use LasHeR for RGBT. Could you please check if the training parameter settings are the same as ours, or use the weight  we provided to verify the results.
