### ISSUE TITLE
Model weights

### ISSUE THREAD

**Issue by setarekhosravi** [SparkTempest/Bi-directional-Adapter#3]
Please share the model weights through Google Drive. I can't download it from Baidu Drive.

**Comment by setarekhosravi** [comment]
Thank you!

**Comment by setarekhosravi** [comment]
When I want to download weights from google drive I see this:
You need access
Request access, or switch to an account with access.
Please fix it.

**Comment by setarekhosravi** [comment]
When I want to download weights from google drive I see this:
You need access
Request access, or switch to an account with access.
Please fix it.

**Comment by SparkTempest** [comment]
> When I want to download weights from google drive I see this: You need access Request access, or switch to an account with access. Please fix it.

Sorry about that, fixed now.

**Comment by setarekhosravi** [comment]
Thank you.
