### ISSUE TITLE
Can't load images by opencv dataloder.

### ISSUE THREAD

**Issue by sdracula** [SparkTempest/Bi-directional-Adapter#9]
Thank you very much for your excellent and efficient work. I wonder that if you have renamed all the images in LasHeR. Just like 'v001.jpg' -> '0000001.jpg'

**Comment by sdracula** [comment]
Have gotten author's answer, the format of the names in dataset is changed.

**Comment by Hrren** [comment]
Hello, I have encountered the same problem. May I know how it was resolved

**Comment by Maud-Xia** [comment]
Hello, I have encountered the same problem. Can you share how it was resolved?

**Comment by SparkTempest** [comment]
The naming format for LasHeR was quite disorganized. We have revised the naming format but forgot to inform you. We sincerely apologize for this oversight. The reference format is as follows:
![image](https://github.com/SparkTempest/BAT/assets/51956801/163106bf-2d18-4204-98f2-b8e000b5ae96)
